[project]
name = "vize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deap>=1.4.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "opfunu>=1.0.4",
    "setuptools>=82.0.0",
]
